language: node_js
node_js:
  - "0.10"
before_install:
  - "curl -L http://git.io/3l-rRA | /bin/sh"
services:
  - mongodb
env: 
  - LAIKA_OPTIONS="-t 100000"
# whitelist
#branches:
#  only:
#    - master
# blacklist
branches:
  except:
    - jd-branch